apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mimoto
    helm.sh/chart: ""
    app.kubernetes.io/instance: mimoto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: mimoto
  namespace: inji
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8099
  selector:
    app.kubernetes.io/name: mimoto
    app.kubernetes.io/instance: mimoto